### ISSUE TITLE
Please add Support for different Gravatar default Avatars

### ISSUE THREAD

**Issue by mogoh** [dokufreaks/plugin-avatar#4]
Gravatar lists several default Avatars. Please add an Option to select one of those.

**Comment by Aleksey-Maksimov** [comment]
I have a similar request.
Please add support selection order of images (fallback) without the use of monster, e.g. gravatar->default (/images/default_<size>.png)

**Comment by michitux** [comment]
As #5 has been merged I consider this implemented. If there are more features to implement please open a new issue.
